### ISSUE TITLE
Python 3.9 compatibility

### ISSUE THREAD

**Issue by vivekthampy** [draustin/pyqtgraph_extensions#3]
There seems to be a compatibility issue with python 3.9. It probably has to do with the version of llvmlite required (<0.33), that apparently is incompatible with python 3.9

**Comment by draustin** [comment]
Thanks for reporting. Yes llvmlite is a dependency of numba which is a dependency of mathx which is a dependency of pyqtgraph_extensions, and llvmlite and numba don't support Python 3.9.

I modified mathx so that it does not require numba - it is a dependency only for 3.6 <= version < 3.9 and released a new version of pyqtgraph_extensions (0.5.2) enforcing this corrected version of mathx.
https://github.com/draustin/pyqtgraph_extensions/releases/tag/0.5.2

**Comment by vivekthampy** [comment]
Oh great! Thanks for the super quick response and fix, Dane. Much
appreciated.
